name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Run coverage
      run: |
        make check-coverage

    - name: Upload coverage to Codecov
      run: |
        CODECOV_NAME=coverage.out bash <(curl -s https://codecov.io/bash)
